import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";


export const metadata: Metadata = {
  title: "AC Repair, Installation and Maintenance Services in Lagos | Reliable and Affordable Solutions | Professional HVAC Services for Your Home and Business",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-max w-screen"
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-pap2kZ7YHQyF..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </head>
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <div className="h-max w-full fixed top-[85%] left-[80%] sm:left-[90%]">
          <a href="https://wa.me/2347047880486" title="whatsapp" target="_blank" rel="noopener noreferrer" className="bg-green-500 text-white p-3 rounded-full shadow-lg hover:bg-green-600 transition-colors duration-300">
            <i className="fa-brands fa-whatsapp text-2xl"></i>
          </a>
        </div>
        <Footer />
        </body>
    </html>
  );
}
