import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/sections/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-max w-screen"
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-pap2kZ7YHQyF..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <Header />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
